### ISSUE TITLE
Error on Running model on a per-TF basis, to get betas on epigenomic and sequence features

### ISSUE THREAD

**Issue by bk11-lab** [immunogenomics/IMPACT#2]
When I try to run `Rscript ENet_fit7.R Tbet Gata3 Stat3 Foxp3`, I get following error message-
[1] 1
Error in classifier_TN_train[, 2] <- ExtraFeatures_negative : 
  number of items to replace is not a multiple of replacement length
Execution halted
I would appreciate your help if someone had came across this error and troubleshot the problem. Thanks in advance.

**Comment by TiffanyAmariuta** [comment]
Hello, 

Thank you for your interest in using IMPACT! Would you please elaborate on your input files? For instance, which file are you using for the following variables: ExtraFeatures, positive_bed, negative_bed? I supplied dummy paths in the code, so that the user may replace them with their own files. How to create those files is outlined in the readme. Let me know if you need further assistance.

Good luck! 

Tiffany

**Comment by bhuwankhatri11** [comment]
I have modified your dummy paths in the code. My input files for ExtraFeatures, positive_bed and negative bed are-
```
ExtraFeatures <- read.table(paste0("/s/lessard/bk/IMPACT/IMPACT-master/Features/ExtraFeatures_update_",args[mastertf],"only_center.txt"),sep = "\t", header = F, stringsAsFactors = FALSE)
	      positive_bed <- read.table(paste0("/s/lessard/bk/IMPACT/IMPACT-master/Training/train_test_positive_bed_",args[mastertf],"only_center.txt"),sep = "\t", header = F, stringsAsFactors = FALSE)
	      negative_bed <- read.table(paste0("/s/lessard/bk/IMPACT/IMPACT-master/Training/train_test_negative_bed_",args[mastertf],"only_center.txt"),sep = "\t", header = F, stringsAsFactors = FALSE)
```

**Comment by TiffanyAmariuta** [comment]
And what do your files look like? What are their dimensions and what do the values look like inside?

**Comment by bhuwankhatri11** [comment]
ExtraFeatures files look like-
```
==> ExtraFeatures_update_Foxp3only_center.txt <==
85.572
120.192
264.823
79.465
65.174
182.273
289.692
92.826
55.184
178.96

==> ExtraFeatures_update_Gata3only_center.txt <==
46.905
190.203
339.102
137.055
153.906
170.119
37.929
118.447
106.636
195.457

==> ExtraFeatures_update_Stat3only_center.txt <==
84.07
67.512
84.454
456.335
71.055
348.954
23.539
247.587
36.758
169.246

==> ExtraFeatures_update_Tbetonly_center.txt <==
39.799
103.049
311.119
78.829
132.934
417.041
240.153
93.287
55.258
250.402
```
```
wc -l ExtraFeatures_update_*
```
13005 ExtraFeatures_update_Foxp3only_center.txt
 13224 ExtraFeatures_update_Gata3only_center.txt
 13181 ExtraFeatures_update_Stat3only_center.txt
 22086 ExtraFeatures_update_Tbetonly_center.tx
```
Positive bed files look like-
```
==> train_test_positive_bed_Foxp3only_center.txt <==
chr12	66684704	66684706	0	0	+
chr8	126963614	126963616	0	0	+
chr18	108433	108435	0	0	+
chr7	68433087	68433089	0	0	+
chr1	100905831	100905833	0	0	+
chr2	39663133	39663135	0	0	+
chr5	100224949	100224951	0	0	+
chr9	92848360	92848362	0	0	+
chr6	88135783	88135785	0	0	+
chr14	95989899	95989901	0	0	+

==> train_test_positive_bed_Gata3only_center.txt <==
chr17	21171631	21171633	0	0	+
chr8	8775459	8775461	0	0	+
chr2	43653838	43653840	0	0	+
chr5	159869944	159869946	0	0	+
chr16	56411441	56411443	0	0	+
chr14	101106928	101106930	0	0	+
chr10	116730343	116730345	0	0	+
chr8	126963614	126963616	0	0	+
chr5	176852923	176852925	0	0	+
chr7	150178816	150178818	0	0	+

==> train_test_positive_bed_Stat3only_center.txt <==
chrX	77359386	77359387	Stat3_Th17	0	+
chr6	11728709	11728710	Stat3_Th17	0	+
chr6	27720884	27720885	Stat3_Th17	0	+
chr1	87795168	87795169	Stat3_Th17	0	+
chr8	128933388	128933389	Stat3_Th17	0	+
chr21	17268828	17268829	Stat3_Th17	0	+
chr3	194117101	194117102	Stat3_Th17	0	+
chr18	46451331	46451332	Stat3_Th17	0	+
chr1	8623291	8623292	Stat3_Th17	0	+
chr6	112295466	112295467	Stat3_Th17	0	+

==> train_test_positive_bed_Tbetonly_center.txt <==
chr9	92023456	92023458	0	0	+
chr1	10992970	10992972	0	0	+
chr17	57407004	57407006	0	0	+
chr16	31879670	31879672	0	0	+
chr12	117537452	117537454	0	0	+
chr1	89148658	89148660	0	0	+
chr15	93427306	93427308	0	0	+
chr1	147986732	147986734	0	0	+
chr5	156181097	156181099	0	0	+
chr11	31531119	31531121	0	0	+
```
negative_bed files:
```
==> train_test_negative_bed_Foxp3only_center.txt <==
chr1	190247398	190247400	Tbet_Th1	1.48651057488521	+
chr5	173682817	173682819	Tbet_Th1	1.48651057488521	+
chr10	121127713	121127715	Tbet_Th1	1.48651057488521	+
chr10	139853925	139853927	Tbet_Th1	1.48651057488521	+
chr6	167892466	167892468	Tbet_Th1	1.42318956271371	+
chrY	109261393	109261395	Tbet_Th1	1.42318956271371	+
chr6	159464665	159464667	Tbet_Th1	1.48651057488521	+
chr12	109304132	109304134	Tbet_Th1	1.48651057488521	+
chr1	213103485	213103487	Tbet_Th1	1.48651057488521	+
chr8	114092453	114092455	Tbet_Th1	1.42318956271371	+

==> train_test_negative_bed_Gata3only_center.txt <==
chr8	114108175	114108177	Tbet_Th1	1.48651057488521	+
chrY	100976781	100976783	Tbet_Th1	1.42318956271371	+
chr5	187184588	187184590	Tbet_Th1	1.42318956271371	+
chr2	164175987	164175989	Tbet_Th1	1.48651057488521	+
chr18	138197915	138197917	Tbet_Th1	1.48651057488521	+
chrX	151586745	151586747	Tbet_Th1	1.42318956271371	+
chr4	137880987	137880989	Tbet_Th1	1.48651057488521	+
chr8	111866159	111866161	Tbet_Th1	1.48651057488521	+
chr4	172524948	172524950	Tbet_Th1	1.42318956271371	+
chr4	109689989	109689991	Tbet_Th1	1.42318956271371	+

==> train_test_negative_bed_Stat3only_center.txt <==
chr1	39301904	39301905	Stat3_Th17	1.45854318023522	+
chr19	58760521	58760522	Stat3_Th17	1.43444580032503	+
chr3	144111420	144111421	Stat3_Th17	1.43444580032503	+
chr10	83078937	83078938	Stat3_Th17	1.43444580032503	+
chr1	238690644	238690645	Stat3_Th17	1.43444580032503	+
chr18	23282019	23282020	Stat3_Th17	1.43444580032503	+
chr2	24387304	24387305	Stat3_Th17	1.43444580032503	+
chr10	130985017	130985018	Stat3_Th17	1.43444580032503	+
chr1	118252116	118252117	Stat3_Th17	1.43444580032503	+
chr2	103140327	103140328	Stat3_Th17	1.43444580032503	+

==> train_test_negative_bed_Tbetonly_center.txt <==
chr8	103905224	103905226	Tbet_Th1	1.42318956271371	+
chr12	112769988	112769990	Tbet_Th1	1.48651057488521	+
chr3	125655668	125655670	Tbet_Th1	1.48651057488521	+
chr4	183701687	183701689	Tbet_Th1	1.42318956271371	+
chr3	193702188	193702190	Tbet_Th1	1.48651057488521	+
chr8	115697010	115697012	Tbet_Th1	1.48651057488521	+
chr4	122393115	122393117	Tbet_Th1	1.48651057488521	+
chr17	130012904	130012906	Tbet_Th1	1.48651057488521	+
chr5	147203812	147203814	Tbet_Th1	1.48651057488521	+
chr20	105070844	105070846	Tbet_Th1	1.48651057488521	+
```

**Comment by TiffanyAmariuta** [comment]
And does the length of each TF's Phastcon conservation score vector (ExtraFeatures) add up to the  sum of the rows in your positive and negative bed files for each TF? You should have one conservation score for each region from both your positive and negative sets.

**Comment by bk11-lab** [comment]
Do I need to run 'PhastconsConservation_center.R` script first to check this?

**Comment by TiffanyAmariuta** [comment]
No, you can check this by making sure your wc -l ExtraFeatures_update_{TF}only_center.txt is equal to nrow(positive_bed) + nrow(negative_bed)

**Comment by bk11-lab** [comment]
By calculating the wc -l ExtraFeatures_update_{TF}only_center.txt is not equal to wc -l positive_bed + wc -l negative_bed. How do I make this equation equal?

**Comment by TiffanyAmariuta** [comment]
What are the values? If you have fewer rows in your ExtraFeatures file, then you did not compute Phastcons conservation for all your training regions (across positive and negative sets).

**Comment by bhuwankhatri11** [comment]
I did not compute Phastcons conservation for the training region. How do I do that? Is it by running  `PhastconsConservation_center.R `?

`wc -l train_test_*Foxp3only*.txt`
14766 train_test_negative_bed_Foxp3only_center.txt
    691 train_test_positive_bed_Foxp3only_center.txt
`wc -l train_test_*Stat3only*.txt`
11791 train_test_negative_bed_Stat3only_center.txt
   1181 train_test_positive_bed_Stat3only_center.txt
`wc -l train_test_*Tbetonly*.txt`
14566 train_test_negative_bed_Tbetonly_center.txt
  16520 train_test_positive_bed_Tbetonly_center.txt
`wc -l train_test_negative_bed_*_center.txt `
14766 train_test_negative_bed_Foxp3only_center.txt
  10000 train_test_negative_bed_Gata3only_center.txt
  11791 train_test_negative_bed_Stat3only_center.txt
  14566 train_test_negative_bed_Tbetonly_center.txt
`wc -l train_test_positive_bed*center.txt`
691 train_test_positive_bed_Foxp3only_center.txt
   691 train_test_positive_bed_Gata3only_center.txt
  1181 train_test_positive_bed_Stat3only_center.txt
 16520 train_test_positive_bed_Tbetonly_center.txt

**Comment by TiffanyAmariuta** [comment]
Yes, precisely. If you did not compute Phastcons, then how did you create the ExtraFeatures files?

**Comment by bk11-lab** [comment]
I used those files that are already present in your repo. It is not very clear from the github wiki steps that's why I am messing around. Could you please points the steps that need to be followed one after another in this process?

**Comment by TiffanyAmariuta** [comment]
The steps that need to be followed one after the other are outlined in detail in the readme. To run IMPACT, you will need to generate your own intermediate files, again by following the readme.

**Comment by bk11-lab** [comment]
Hi,

Would you please tell me how you generated Motif_Foxp3_Treg.txt, Motif_Gata3_Th2.txt, Motif_Stat3_Th17.txt and Motif_Tbet_Th1.txt files?
I will appreciate your help. Thanks!

**Comment by TiffanyAmariuta** [comment]
Hello, 

These files are from Homer's database of TF position weight matrices.

**Comment by bhuwankhatri11** [comment]
Thank you for the information. 
I am at the second step of IMPACT but getting an error. Would you please let me know what might be wrong?
When I run Rscript ENet_fit7.R Tbet Gata3 Stat3 Foxp3 gives me following error-
[1] 1
[1] "chr1"
Error in which(seqnames(positive_bed_Granges) == chromosomes[chrom]) : 
  argument to 'which' is not logical
Calls: which -> which
Execution halted

Thanks.

**Comment by TiffanyAmariuta** [comment]
Hello, 

As the error says, your argument to the which() function is not logical, which is what it needs to be. You should see a list of chromosome indicators, i.e. c("chr1", "chr1", ... ) for this variable: seqnames(positive_bed_Granges). chromosomes[chrom] should look like "chr1" (or whatever chromosome you are working on).

**Comment by bhuwankhatri11** [comment]
seqnames(positive_bed_Granges) gives me this output.
factor-Rle of length 996 with 955 runs
  Lengths:     1     1     1     1     1     1     1     1     1     1     1     1 ...     1     1     1     1     1     1     1     2     1     1     1     1
  Values :  chr6  chrY  chr2 chr14 chr10  chr3 chr11  chr6  chr2 chr15 chr21 chr19 ...  chr4 chr11  chr2  chr8 chr14  chr6 chr18  chr2  chr7  chr6  chr1  chr6
Levels(24): chr1 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr2 chr20 chr21 chr22 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chrX chrY

But, 
seqnames(positive_bed_Granges@seqinfo) gives
 [1] "chr1"  "chr10" "chr11" "chr12" "chr13" "chr14" "chr15" "chr16" "chr17" "chr18" "chr19" "chr2"  "chr20" "chr21" "chr22" "chr3"  "chr4"  "chr5"  "chr6" 
[20] "chr7"  "chr8"  "chr9"  "chrX"  "chrY"

When I replaced seqnames(positive_bed_Granges) with seqnames(positive_bed_Granges@seqinfo), I got error like this:

Warning messages:
1: In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': chr18
  - in 'y': chr11, chr12, chr14, chr15, chr16, chr17, chr2, chr20, chr21, chr22, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chrX
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).
2: In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': chr18
  - in 'y': chr11, chr12, chr14, chr15, chr16, chr17, chr2, chr20, chr21, chr22, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chrX
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).
3: In .Seqinfo.mergexy(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': chr18
  - in 'y': chr11, chr12, chr14, chr15, chr16, chr17, chr2, chr20, chr21, chr22, chr3, chr4, chr5, chr6, chr7, chr8, chr9, chrX
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).

FYI
I am working with Rscript ENet_fit7.R Tbet Gata3 Stat3 Foxp3

**Comment by TiffanyAmariuta** [comment]
The warning message is not an error message. Looks like you just didn't have any motifs on chr18, which is strange, but should not prevent your script from running.

**Comment by bhuwankhatri11** [comment]
Hi,

I have solve that error but am getting another error now while generating RData of genome bed.

Rscript genome_to_bed.R
[1] 1
Error in genemat[, 2] <- seq(start, end, resolution) : 
  number of items to replace is not a multiple of replacement length
Execution halted

Would you please help me to figure this out?
Thanks.

**Comment by TiffanyAmariuta** [comment]
Hello Bhuwan, 

The issue section of the IMPACT github is for IMPACT-related issues, not fundamental R scripting questions. Please refer to any number of R tutorials online to debug your code, such as https://www.statmethods.net/r-tutorial/index.html or https://www.datamentor.io/r-programming/ Please refrain from posting issues with your code unrelated to the IMPACT method. Good luck!

**Comment by bhuwankhatri11** [comment]
I am sorry for asking basic R questions. 
Would you please tell me why I am getting the same value for all chromosomes when I run

#!/bin/bash
#BSUB -q big
#BSUB -n 4
#BSUB -R rusage[mem=200000]
#BSUB -J "myArray[1-24]" myJob
#BSUB -o /data/srlab/amariuta/jobs/ClassiferRegMap/Fig1/GenomeWide/GenomeTracks/job.out

module load R/3.2.2
TF=Stat4
Rscript --verbose Predictvalues_TFarg.R ${TF},${LSB_JOBINDEX} > Predictvalues_TFarg_${LSB_JOBINDEX}_${TF}.Rout 

The values for all chromosomes are the same look like this-
zcat Gata3_IMPACT_predictions_chr1.txt.gz |head 
V1
0.090184386672837
0.090184386672837
0.090184386672837
0.090184386672837
0.090184386672837
0.090184386672837
0.090184386672837
0.090184386672837
0.090184386672837
This gives me the same minimum and maximum values per chromosome in the subsequent step. And thus final logistic regression scale becomes NA.
I will appreciate your help.
