### ISSUE TITLE
*.M_5_50 files of IMPACT707 LDscores are missing

### ISSUE THREAD

**Issue by JiaShun-Xiao** [immunogenomics/IMPACT#3]
excuse me, I noticed that *.M_5_50 files of IMPACT707 LDscores are missing, could you please upload them!

**Comment by TiffanyAmariuta** [comment]
Hello, thank you for pointing this out! You can now find the M_5_50 counts (number of SNPs with MAF > 5%) at IMPACT/tree/master/IMPACT707/LDscores/*M_5_50.gz
