### ISSUE TITLE
How to download large files

### ISSUE THREAD

**Issue by bschilder** [immunogenomics/IMPACT#4]
Hello, 

Is there an API to download the large files stored in the IMPACT707 subfolders? It seems like cloning and pulling the full files requires having a paid Git-LFS subscription, essentially putting them behind a paywall. Though I am new to LFS so perhaps I'm missing something.

Thanks for your help and this awesome resource!

-Brian 

```
(base) [schilb03@lc02a27 data]$ git clone https://github.com/immunogenomics/IMPACT.git
Cloning into 'IMPACT'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 1547 (delta 3), reused 9 (delta 3), pack-reused 1535
Receiving objects: 100% (1547/1547), 617.91 MiB | 108.34 MiB/s, done.
Resolving deltas: 100% (245/245), done.
Checking connectivity... done.
Downloading IMPACT707/Annotations/IMPACT707_EAS_chr1.annot.gz (499 MB)
Error downloading object: IMPACT707/Annotations/IMPACT707_EAS_chr1.annot.gz (747b5fc): Smudge error: Error downloading IMPACT707/Annotations/IMPACT707_EAS_chr1.annot.gz (747b5fc7a0af1cfd1921e1f97cc1a4bb2aa60ae30261d4481c74ecb772c8bb83): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /sc/orga/projects/pd-omics/data/IMPACT/.git/lfs/logs/20200316T143403.209454725.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: IMPACT707/Annotations/IMPACT707_EAS_chr1.annot.gz: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
(base) [schilb03@lc02a27 data]$ cd IMPACT/
(base) [schilb03@lc02a27 IMPACT]$ git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                     
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/immunogenomics/IMPACT.git/info/lfs'
```

**Comment by TiffanyAmariuta** [comment]
Hi Brian, 

Thanks for posting this! Due to these unforeseen restrictions on bandwidth (a metric we cannot control ourselves) I am currently working on migrating files from Github to Dropbox. I will update you and the readme of this repository once the migration is made. 

Best, 

Tiffany

**Comment by TiffanyAmariuta** [comment]
Hi Brian, 

It has been brought to my attention that we have purchased a second data pack which allowed us more bandwidth, which should theoretically remove the paywall. If you try cloning again, please let me know if it works. On my end, things seem to be working as usual. 

Best, 

Tiffany

**Comment by bschilder** [comment]
Hi Tiffany, 

Thanks! I'm able to start downloading the files now; the only error I'm running into I think is due to my unstable internet connection (currently the cloning crashes partway through). I'll keep trying and see if I can get it to work all the way.
```
git clone https://github.com/immunogenomics/IMPACT.git                 (base) 
Cloning into 'IMPACT'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (9/9), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```
-Brian

**Comment by TiffanyAmariuta** [comment]
Hi Brian, 

I have also experienced "the remote end [hanging] up unexpectedly". I am surprised that this error happens with the normal git clone command- because this is prior to the "git lfs pull" step which brings in all the large files. Therefore, perhaps increasing your buffer might help. I think this thread might help: https://stackoverflow.com/questions/6842687/the-remote-end-hung-up-unexpectedly-while-git-cloning 

If that doesn't resolve it, another suggestion might be to run the clone as a job rather than an interactive session. As you mentioned it might be a connectivity issue; which is possible since the original git clone shouldn't be pulling in any lfs files. 

This thread might also be of interest suggesting a better internet connection indeed helps: https://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining

Best, 

Tiffany

**Comment by bschilder** [comment]
Raising the buffer size did the trick! Took a couple hours on my laptop but all the files are there now. 

Thanks so much for the advice!

-Brian

**Comment by TiffanyAmariuta** [comment]
Amazing! Thanks for the update! Still sorry it took so long on your local machine- when I tested it on our server it was pretty fast (for ~17Gb of LFS data). 

-Tiffany

**Comment by bschilder** [comment]
Might just be my internet being wacky, it's all good tho!
