### ISSUE TITLE
Where to download annot.gz files

### ISSUE THREAD

**Issue by FarhangAgh** [immunogenomics/IMPACT#6]
Hi,

May I know from where we can download .annot.gz files for EUR and EAS?

Thank you for your help and fantastic software.

-Farhang

**Comment by TiffanyAmariuta** [comment]
Hello! Thank you for your interest in IMPACT! Apologies for the late response to your issue. annot.gz files can be found here: https://github.com/immunogenomics/IMPACT/tree/master/IMPACT707/Annotations

Please let me know if you have more questions! 

Best, 

Tiffany
